### ISSUE TITLE
Tried everything 

### ISSUE THREAD

**Issue by DiogoKarma** [Theblockbuster1/disboard-auto-bump#10]
Heya i tried and still doenst work xd

**Comment by DiogoKarma** [comment]
![image](https://user-images.githubusercontent.com/78310786/106392810-82ed8280-63eb-11eb-959a-4fbe89ba949d.png)
it says this tho

**Comment by Theblockbuster1** [comment]
Can you expand the second error? Also instead of opening a new issue it would be better if you reopened the previous issue (too late now..). As it says in the [FAQ](https://github.com/Theblockbuster1/disboard-auto-bump#faq), the first error is completely normal. From what I can see, I assume that the second error is from an error checking for updates, which shouldn't really break the extension.

**Comment by DiogoKarma** [comment]
sorry i didnt know how to reopen it.. heres the other error tho
![image](https://user-images.githubusercontent.com/78310786/107507613-bc668080-6b97-11eb-83d8-b0ddffdbf545.png)

**Comment by Theblockbuster1** [comment]
Oh that screenshot helps a lot - seems that it's an issue with the Portuguese version of Disboard. I'll release a patch update very soon!

**Comment by DiogoKarma** [comment]
oh ok! thank you very much

**Comment by Theblockbuster1** [comment]
Should be fixed!

**Comment by DiogoKarma** [comment]
nope its still the same xd

**Comment by DiogoKarma** [comment]
for some reason everytime i bump it it says this 
![image](https://user-images.githubusercontent.com/78310786/107838222-b8578000-6d9c-11eb-8df4-9df51421564a.png)

**Comment by DiogoKarma** [comment]
![image](https://user-images.githubusercontent.com/78310786/107838259-f2288680-6d9c-11eb-8794-e835e82ae3aa.png)
and this

**Comment by Theblockbuster1** [comment]
@DiogoKarma Please make new issues for different problems. This problem is unrelated to the original issue which you opened 2 weeks ago. However, I'm not sure why this is happening... is there anything in the 'Errors' page?
