### ISSUE TITLE
Raspberry Pi support?

### ISSUE THREAD

**Issue by PyricDemon** [Theblockbuster1/disboard-auto-bump#23]
I installed Firefox on the single board computer called Raspberry Pi. I put the extension in Firefox and Firefox recognizes it and it's permissions.

The problem is the extension doesn't affect the page in anyway, I do not see the B or the timer for the next bump.
![20211214_204715](https://user-images.githubusercontent.com/79799834/146107873-adac5b22-d3e1-4a43-99e5-e584a69c8e70.jpg)

**Comment by Theblockbuster1** [comment]
From my experience, it works on a Raspberry Pi, however I used Chromium. If you've imported the extension it should appear on the top bar, so perhaps you have not properly done so. Maybe check [the instructions in the readme](https://github.com/Theblockbuster1/disboard-auto-bump#install-instructions-firefox). If it still doesn't work after refreshing, you could try using Chromium, because I don't have as much experience using Firefox.

**Comment by PyricDemon** [comment]
Ah okay, I had specifically Uninstalled chromium because I do not like it, but google chrome is too cpu intensive so I went with Firefox. I'll switch back and see if it works, thanks for the info.

**Comment by PyricDemon** [comment]
Sorry about the extreme delay! Yes, it does work perfectly on chromium. Thank you.
